### ISSUE TITLE
Reconnected bug in colab

### ISSUE THREAD

**Issue by NoA2647** [erfan-sams/twitter-scraper#1]
When I run this code and restart the colab, the colab is thrown into the loop to reconnect
code:
! curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py 
! python3 get-pip.py --force-reinstall 

 i suggest use this code for this problem, it work for me and it's fine
code:
! curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py 
! python3 get-pip.py

**Comment by erfan-sams** [comment]
Please if it is possible share your colab notebook link because that's works for me without any error!

**Comment by erfan-sams** [comment]
> 

Please if it is possible share your colab notebook link because that's works for me without any error or reconnected!

**Comment by erfan-sams** [comment]
> When I run this code and restart the colab, the colab is thrown into the loop to reconnect code:! curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py ! python3 get-pip.py --force-reinstall
> 
> I suggest using this code for this problem, it works for me, and it's fine code:! curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py ! python3 get-pip.py

Please, if it is possible, share your colab notebook link because that works for me without any error or reconnecting!
